version: 2.1

jobs:
  run-tests:
    docker:
      - image: cimg/node:16.11.1
        auth:
          username: dannyoka
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: "build docker image"
          command: "docker build -f Dockerfile.dev -t dannyoka/docker-react ."

workflows:
  test-workflow:
    jobs:
      - run-tests
