version: 2.1

jobs:
  run-tests:
    docker:
      - image: cimg/node:14
    steps:
      - checkout
      - run:
          name: "build docker image"
          command: "echo Hello world!"

workflows:
  test-workflow:
    jobs:
      - run-tests
